config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # resources :tasks
  # digital `rails routes` per vedere tutte le routes che hai
  # se ne vuoi generate solo specifiche, usa:
  # resources :tasks, only: [:index, :show, :delete]
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'

  get 'tasks/:id', to: 'tasks#show', as: 'task'

  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy', as: 'delete'

  post '/tasks', to: 'tasks#create', as: 'create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: 'edit'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController


  # READ ALL
  def index
    @tasks = Task.all
  end

  # READ ONE
  def show
    @task = Task.find(params[:id])
  end

  # UPDATE PATCH form
  def update
    @task.update(task_params)
    redirect_to task
  end

  # CREATE GET
  def new
    @task = Task.new
  end

  # CREATE POST
  def create
    @task = Task.new(task_params)
    @task.save
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  # DELETE
  def destroy
    @task = Task.find(params[:id])
    @task.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/create.html.erb
 <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :details %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Return to Tasks", tasks_path %>

app/views/tasks/edit.html.erb
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>


<%= link_to "Return to Tasks", tasks_path %>

app/views/tasks/index.html.erb
<ol>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task %></li>
    <% if task.completed %>
      <p>[x]</p>
    <% else %>
      <p>[ ]</p>
    <% end %>
  <% end %>
</ol>


<%= link_to "Create new Tasks", tasks_new_path %>

<!-- <%= link_to "Tutti i nomi delle task", tasks_path %> -->

<!-- mettendolink_to sopra con task.title e task_path sto praticamente facendo comparire tutti i nomi delle task ma in questo caso saranno tutti cliccabili perchè la frase "task" si riferisce all'action show come posso vedere dal file routes dove sulla destra c'è as: 'task' (task l'ho deciso io come parola...poteva essere banana) che è una parola chiave che uso per riferirmi al percorso di quel particolare metodo/action. Nel caso in cui non avessi usato la parola chiave avrei dovuto scrivere: task_path(@task) che sta per /tasks/:id. mentre per tasks/:id/edit avrei dovuto scrivere: edit_task_path(@task) -->

app/views/tasks/new.html.erb
 <%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.submit %>
<% end %>

<%= link_to "Return to Tasks", tasks_path %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<p><%= @task.completed %></p>

<%= link_to "Return to Tasks", tasks_path %>

<%= link_to "Delete Tasks", @task, method: :delete %>